# Generated by Django 2.2.1 on 2019-10-17 04:04

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='电子邮箱')),
                ('avatar', models.ImageField(null=True, upload_to=user.models.upload_to_user_path)),
                ('nickname', models.CharField(max_length=10, unique=True, verbose_name='昵称')),
                ('profile', models.CharField(blank=True, max_length=200, verbose_name='个人简介')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
